import type { Metadata } from "next";
import {Kantumruy_Pro } from "next/font/google";
import "./globals.css";

import NavBar from "./components/NavBar/Index";

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import { UserProvider } from "@/Context";

const KantumruySans = Kantumruy_Pro({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${KantumruySans.className}antialiased`}
        suppressHydrationWarning
      >
      <UserProvider>
        <NavBar/>
        {children}
        <ToastContainer />
      </UserProvider>
      </body>
    </html>
  );
}
